language: java

jdk:
#  - oraclejdk7
  - oraclejdk8
#  - openjdk6
#  - openjdk7

script:
    mvn -version;
    mvn -B -U -f pom-aggregator/pom.xml clean test -DTRAVIS_CI;

after_success:

after_failure:

notifications:

email:
    - ci@as-development.net
