/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific
 * language governing permissions and limitations under the License.
 */
//=============================================================================
// DO NOT EDIT THIS FILE. ITS GENERATED AUTOMATICALLY.
//
// Create a file as 'marker' only so the process knows where such
// test suite must be placed. Put a simple class into that file and
// add an annotation which define the type of test suite you wish to declare.
//=============================================================================

package test.net.as_development.tools.reflection;

import org.junit.runner.RunWith;
import org.junit.runners.Suite;

@RunWith(Suite.class)
@Suite.SuiteClasses
({
    test.net.as_development.tools.reflection.AnnotationSearchTest.class,
    test.net.as_development.tools.reflection.ObjectManipulationTest.class,
    test.net.as_development.tools.reflection.PackageUtilsTest.class
})
public class JUnit4TestSuite
{
    // the class remains completely empty,
    // being used only as a holder for the above annotations.
}
