/**
 * This is free and unencumbered software released into the public domain.
 *
 * Anyone is free to copy, modify, publish, use, compile, sell, or
 * distribute this software, either in source code form or as a compiled
 * binary, for any purpose, commercial or non-commercial, and by any
 * means.
 *
 * In jurisdictions that recognize copyright laws, the author or authors
 * of this software dedicate any and all copyright interest in the
 * software to the public domain. We make this dedication for the benefit
 * of the public at large and to the detriment of our heirs and
 * successors. We intend this dedication to be an overt act of
 * relinquishment in perpetuity of all present and future rights to this
 * software under copyright law.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
 * OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *
 * For more information, please refer to <http://unlicense.org/>
 */
//=============================================================================
// DO NOT EDIT THIS FILE. ITS GENERATED AUTOMATICALLY.
//
// Create a file as 'marker' only so the process knows where such
// test suite must be placed. Put a simple class into that file and
// add an annotation which define the type of test suite you wish to declare.
//=============================================================================

package test.net.as_development.asdk.db_service;

import org.junit.runner.RunWith;
import org.junit.runners.Suite;

@RunWith(Suite.class)
@Suite.SuiteClasses
({
    test.net.as_development.asdk.db_service.DBItemBaseTest.class,
    test.net.as_development.asdk.db_service.impl.AttributeListMetaInfoTest.class,
    test.net.as_development.asdk.db_service.impl.backend.creator.DBCreatorTest.class,
    test.net.as_development.asdk.db_service.impl.backend.mongodb.NextTokenTest.class,
    test.net.as_development.asdk.db_service.impl.CompleteButGenericDBTest.class,
    test.net.as_development.asdk.db_service.impl.DBQueryTest.class,
    test.net.as_development.asdk.db_service.impl.DBTest.class,
    test.net.as_development.asdk.db_service.impl.DynamicArrayListTest.class,
    test.net.as_development.asdk.db_service.impl.EntityBaseTest.class,
    test.net.as_development.asdk.db_service.impl.EntityMetaInfoProviderTest.class,
    test.net.as_development.asdk.db_service.impl.simpledb.DecimalStringUtilsTest.class,
    test.net.as_development.asdk.db_service.impl.simpledb.NumberStringUtilsTest.class,
    test.net.as_development.asdk.db_service.impl.simpledb.SdbDatatypeConvertTest.class,
    test.net.as_development.asdk.db_service.impl.sql.AnsiSqlGeneratorTest.class,
    test.net.as_development.asdk.db_service.impl.sql.SqlProviderTest.class,
    test.net.as_development.asdk.db_service.impl.sql.SqlStatementCacheTest.class,
    test.net.as_development.asdk.db_service.impl.server.DBBackupTest.class
})
public class JUnit4TestSuite
{
    // the class remains completely empty,
    // being used only as a holder for the above annotations.
}
